import { library } from '@fortawesome/fontawesome-svg-core';

// import your icons
import {
  faPlus,
  faChevronDown,
  faBookmark as faBookmarkSolid,
  faBars,
  faCog,
  faSignOutAlt,
  faCompass,
  faUser,
  faHome,
  // faLightbulb,
  faMinus,
  faListUl,
  faListOl,
  faPencilAlt,
  faChevronRight,
  faSignInAlt,
  faEllipsisH,
  faLink,
  faImage,
  faCircleNotch,
  faHeading,
  faBold,
  faItalic,
  faUnderline,
  faCode,
} from '@fortawesome/free-solid-svg-icons'

import {
  faBookmark as faBookmarkRegular,
  faImages,
  faLightbulb,
  faCommentAlt,
  faEdit,
  faTrashAlt,
  faClock,
} from '@fortawesome/free-regular-svg-icons'

library.add(
  faPlus,
  faChevronDown,
  faBookmarkSolid,
  faBookmarkRegular,
  faBars,
  faCog,
  faSignOutAlt,
  faCompass,
  faUser,
  faHome,
  faLightbulb,
  faImages,
  faMinus,
  faListUl,
  faListOl,
  faPencilAlt,
  faChevronRight,
  faSignInAlt,
  faCommentAlt,
  faEdit,
  faTrashAlt,
  faEllipsisH,
  faLink,
  faImage,
  faClock,
  faCircleNotch,
  faHeading,
  faBold,
  faItalic,
  faUnderline,
  faCode,
)
