jobs:
  include:
    - language: node_js
      node_js:
        - 'node'
        - '12'

      before_script:
        - cd client
        - npm install

    - language: go
      go:
        - '1.x'
        - 'master'

      before_script:
        - cd server

      script:
        - go test -v ./...


