jobs:
  include:
    #- language: node_js
    #  node_js: node

    #  before_script:
    #    - cd next-client
    #    - npm install

    - language: go
      go: master

      before_install:
        - cd server

      script:
        - go test -v ./...


